In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("echipe_UCL.csv", index_col=0)
df.describe()

       trophies
count  25.00000
mean    2.84000
std     3.13156
min     1.00000
25%     1.00000
50%     2.00000
75%     3.00000
max    15.00000

In [7]:
df.head(10)

       country            team  trophies
0        Spain     Real Madrid      15.0
1        Italy        AC Milan       7.0
2      England       Liverpool       6.0
3      Germany  Bayern Munchen       6.0
4        Spain       Barcelona       5.0
5  Netherlands  Ajax Amsterdam       4.0
6      England      Man United       3.0
7        Italy           Inter       3.0
8      England         Chelsea       2.0
9      England    Nottm Forest       2.0

In [8]:
df[df["country"] == "England"]

    country             team  trophies
2   England        Liverpool       6.0
6   England       Man United       3.0
8   England          Chelsea       2.0
9   England     Nottm Forest       2.0
13  England      Aston Villa       1.0
14  England         Man City       1.0
15  England  Manchester City       1.0