In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1. Importați fișierul CSV folosind Pandas și afișați primele 5 rânduri. 
# 2. Afișați tipurile de date ale fiecărei coloane. 
# 3. Obțineți statisticile rezumate ale coloanelor numerice din date. 
# 4. Verificați dacă există valori lipsă în setul de date. 
# 5. Numărați câte țări se află în total între câștigătoare, și câte între finaliste
# 6. Selectați și afișați coloanele „an” și „câștigător”. 
# 7. Selectați rândurile în care țara câștigătoare este „Anglia”.

In [4]:
df = pd.read_csv("World_Cup.csv")
#1
df.head(5)

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26

In [5]:
df.dtypes

Year               int64
Country           object
Winner            object
Runners-Up        object
Third             object
Fourth            object
GoalsScored        int64
QualifiedTeams     int64
MatchesPlayed      int64
dtype: object

In [6]:
df.describe()

              Year  GoalsScored  QualifiedTeams  MatchesPlayed
count    22.000000    22.000000       22.000000      22.000000
mean   1978.909091   123.636364       22.227273      43.818182
std      27.738419    34.841882        7.602830      17.632860
min    1930.000000    70.000000       13.000000      17.000000
25%    1959.000000    90.500000       16.000000      32.000000
50%    1980.000000   129.000000       20.000000      45.000000
75%    2001.000000   146.750000       32.000000      64.000000
max    2022.000000   172.000000       32.000000      64.000000

In [ ]:
# 4. Verificați dacă există valori lipsă în setul de date. 
df.isnull().sum()

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
dtype: int64

In [8]:
# 5. Numărați câte țări se află în total între câștigătoare, și câte între finaliste
df["Winner"].unique()

array(['Uruguay', 'Italy', 'Germany FR', 'Brazil', 'England', 'Argentina',
       'France', 'Spain', 'Germany'], dtype=object)

In [12]:
df["Winner"].nunique()

9

In [13]:
df["Runners-Up"].unique()

array(['Argentina', 'Czechoslovakia', 'Hungary', 'Brazil', 'Sweden',
       'Germany FR', 'Italy', 'Netherlands', 'Germany', 'France',
       'Croatia'], dtype=object)

In [11]:
df["Runners-Up"].nunique()

11

In [14]:
df[["Year", "Winner"]]

    Year      Winner
0   1930     Uruguay
1   1934       Italy
2   1938       Italy
3   1950     Uruguay
4   1954  Germany FR
5   1958      Brazil
6   1962      Brazil
7   1966     England
8   1970      Brazil
9   1974  Germany FR
10  1978   Argentina
11  1982       Italy
12  1986   Argentina
13  1990  Germany FR
14  1994      Brazil
15  1998      France
16  2002      Brazil
17  2006       Italy
18  2010       Spain
19  2014     Germany
20  2018      France
21  2022   Argentina

In [15]:
df[df["Country"] == "England"]

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32