In [9]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import matplotlib.animation as animation
from IPython.display import HTML

In [10]:
OPTIONS = ["paper", "rock", "scissors"]

In [11]:
OUTCOME = ["win", "draw", "loss"]

In [12]:
def game_outcome (player, computer):
    if player == computer: return OUTCOME[1]

    if player == OPTIONS[0] :
        if computer == OPTIONS[2]: return OUTCOME[2]
        else:  return OUTCOME[0]

    if player == OPTIONS[1] :
        if computer == OPTIONS[0]: return OUTCOME[2]
        else:  return OUTCOME[0]
        
    if player == OPTIONS[2] :
        if computer == OPTIONS[1]: return OUTCOME[2]
        else:  return OUTCOME[0]

In [13]:
df = pd.DataFrame(
    { "player": [], "computer":[], "outcome": []}
)
df

Empty DataFrame
Columns: [player, computer, outcome]
Index: []

In [23]:
games = []

while True:
    player = input("Introduceți o valoare (Paper, Rock şi Scissors )").lower()

    if player == "exit":
        break 
    
    while player not in OPTIONS:
        player = input("Introduceți o valoare (Paper, Rock şi Scissors )").lower()

    computer = str(np.random.choice(OPTIONS))
    print("Player: ", player, "Computer:", computer,  game_outcome (player, computer))

    games.append([player, computer, game_outcome (player, computer)])

Player:  rock Computer: rock draw
Player:  paper Computer: rock win
Player:  rock Computer: scissors win
Player:  rock Computer: rock draw
Player:  paper Computer: scissors loss
Player:  scissors Computer: paper win
Player:  paper Computer: rock win
Player:  rock Computer: paper loss
Player:  rock Computer: scissors win
Player:  paper Computer: paper draw
Player:  rock Computer: paper loss
Player:  paper Computer: scissors loss
Player:  scissors Computer: rock loss
Player:  scissors Computer: scissors draw

In [24]:
df = pd.DataFrame(games, columns=["player", "computer", "outcome"]
    
)
df.to_csv("games.csv")

In [25]:
df

      player  computer outcome
0       rock      rock    draw
1      paper      rock     win
2       rock  scissors     win
3       rock      rock    draw
4      paper  scissors    loss
5   scissors     paper     win
6      paper      rock     win
7       rock     paper    loss
8       rock  scissors     win
9      paper     paper    draw
10      rock     paper    loss
11     paper  scissors    loss
12  scissors      rock    loss
13  scissors  scissors    draw

In [ ]:
# df = pd.concat([df, df1], axis=0).reset_index(drop=True)
# df.to_csv("games.csv")

In [ ]:
df.outcome.value_counts()

np.int64(5)

In [34]:
df

      player  computer outcome
0       rock      rock    draw
1      paper      rock     win
2       rock  scissors     win
3       rock      rock    draw
4      paper  scissors    loss
5   scissors     paper     win
6      paper      rock     win
7       rock     paper    loss
8       rock  scissors     win
9      paper     paper    draw
10      rock     paper    loss
11     paper  scissors    loss
12  scissors      rock    loss
13  scissors  scissors    draw
14      rock     paper    loss
15     paper  scissors    loss
16     paper  scissors    loss
17  scissors  scissors    draw
18     paper     paper    draw
19      rock      rock    draw
20      rock      rock    draw
21      rock     paper    loss
22     paper  scissors    loss
23     paper  scissors    loss
24  scissors  scissors    draw
25     paper     paper    draw
26      rock      rock    draw
27      rock      rock    draw

In [50]:
df[df.index <= 0]["outcome"].value_counts()

outcome
draw    1
Name: count, dtype: int64

In [51]:
df[df.index <= 0]["outcome"].value_counts().get("win",0)

0

In [47]:
figure, axis = plt.subplots()


BAR_OPTIONS = ["player", "draw", "computer"]

def update_function(index):
    axis.clear()

    current_df = df[df.index <= index]
    values = current_df["outcome"].value_counts()    
    CURRENT_OUTCOME = [values.get("win", 0), values.get("draw", 0), values.get("loss", 0)]

    bars = axis.bar(BAR_OPTIONS, CURRENT_OUTCOME, color="skyblue")


    axis.set_ylabel("Games Played")
    axis.set_xlabel("Outcome")
    
    return bars

ani = animation.FuncAnimation(fig=figure, func=update_function, frames=df.index, repeat=True, interval=2000)
ani.save("games.gif", writer="ffmpeg")



plt.close();
HTML(ani.to_jshtml())